##
# Makefile for automake
##
# Wilfredo Sanchez | wsanchez@apple.com
##

# Project info
Project  = automake
UserType = Developer
ToolType = Commands

# It's a GNU Source project
include $(MAKEFILEPATH)/CoreOS/ReleaseControl/GNUSource.make
