# Can't build IORegistryExplorer without AppKit
APPKIT_FRAMEWORK = $(NSFRAMEWORKDIR)/Appkit.framework
ifeq "$(wildcard $(APPKIT_FRAMEWORK))" ""
SUBPROJECTS := $(filter-out IORegistryExplorer, $(SUBPROJECTS))
IMPLICIT_SOURCE_FILES += IORegistryExplorer
endif

include $(MAKEFILEPATH)/CoreOS/ProjectBuilder/Makefile.Preamble.Common
