export MakeInc_cmd=${SRCROOT}/makedefs/MakeInc.cmd
export MakeInc_def=${SRCROOT}/makedefs/MakeInc.def
export MakeInc_rule=${SRCROOT}/makedefs/MakeInc.rule
export MakeInc_dir=${SRCROOT}/makedefs/MakeInc.dir


include $(MakeInc_cmd)
include $(MakeInc_def)

INSTINC_SUBDIRS = \

INSTINC_SUBDIRS_PPC = \

INSTINC_SUBDIRS_I386 = \

EXPINC_SUBDIRS = \

EXPINC_SUBDIRS_PPC = \

EXPINC_SUBDIRS_I386 = \

DATAFILES = \
	bootp.h  icmp_var.h if_ether.h if_fddi.h   igmp.h  igmp_var.h  \
	in.h in_pcb.h in_systm.h in_var.h ip.h   ip_icmp.h ip_mroute.h \
	ip_var.h tcp.h  tcp_debug.h tcp_fsm.h tcp_seq.h tcp_timer.h \
	tcp_var.h tcpip.h udp.h udp_var.h ip_fw.h ip_dummynet.h


INSTALL_MI_LIST	= ${DATAFILES}

INSTALL_MI_DIR = bsd/netinet

EXPORT_MI_LIST	= ${DATAFILES}

EXPORT_MI_DIR = netinet


include $(MakeInc_rule)
include $(MakeInc_dir)


