include $(CoreOSMakefiles)/ProjectBuilder/Makefile.Postamble.Common

install_resources:
	$(INSTALL_DIRECTORY) $(DSTROOT)$(INSTALLDIR)
	$(INSTALL_FILE) -c StartupParameters.plist $(DSTROOT)$(INSTALLDIR)
