#
# libposix makefile
# $Id: Makefile,v 1.1.1.1 2000/01/20 21:20:17 wsanchez Exp $
#

ARCHFLAGS = 

SRCS = libposix.c
OBJS = libposix.o

CFLAGS = -O -D_POSIX_SOURCE $(ARCHFLAGS)

all: $(OBJS)

clean:
	rm -f *.o *~ core

