##
# Makefile for groff
##

# Project info
Project           = groff
UserType          = Administration
ToolType          = Commands
Extra_Environment = LIBM=""

# It's a GNU Source project
include $(MAKEFILEPATH)/CoreOS/ReleaseControl/GNUSource.make
