export MakeInc_cmd=${SRCROOT}/makedefs/MakeInc.cmd
export MakeInc_def=${SRCROOT}/makedefs/MakeInc.def
export MakeInc_rule=${SRCROOT}/makedefs/MakeInc.rule
export MakeInc_dir=${SRCROOT}/makedefs/MakeInc.dir


include $(MakeInc_cmd)
include $(MakeInc_def)

INSTINC_SUBDIRS = \

INSTINC_SUBDIRS_PPC = \

INSTINC_SUBDIRS_I386 = \

EXPINC_SUBDIRS = \

EXPINC_SUBDIRS_PPC = \

EXPINC_SUBDIRS_I386 = \

DATAFILES= \
	bpf.h hostcache.h if_llc.h if_sppp.h ndrv.h raw_cb.h \
	if.h if_media.h if_tun.h netbuf.h route.h \
	bpfdesc.h if_arp.h if_mib.h if_tunvar.h netisr.h slcompress.h \
	bridge.h if_atm.h if_ppp.h if_types.h ppp_comp.h slip.h \
	etherdefs.h if_blue.h if_pppvar.h if_var.h kext_net.h ppp_defs.h zlib.h \
	ethernet.h if_dl.h if_slvar.h if_vlan_var.h radix.h dlil.h

INSTALL_MI_LIST	= ${DATAFILES}

INSTALL_MI_DIR = bsd/net

EXPORT_MI_LIST	= ${DATAFILES}

EXPORT_MI_DIR = net


include $(MakeInc_rule)
include $(MakeInc_dir)
