#!/bin/sh

##
# Multi-user startup script.
#
# Customize system startup by adding scripts to the startup 
# directory, rather than editing this file.
##

##
# Set shell to ignore Control-C, etc.
# Prevent lusers from shooting themselves in the foot.
##
stty intr  undef
stty kill  undef
stty quit  undef
stty susp  undef
stty start undef
stty stop  undef
stty dsusp undef

. /etc/rc.common

stty status '^T'

##
# Handle arguments passed from init.
##
BootType=${1:-multiuser}

##
# Display a startup message.
##

PercentBoot=0
VerboseFlag=""

echo ""

ConsoleMessage "Initializing system."

case "${BootType}" in
  "autoboot")
    ConsoleMessage "Automatic reboot in progress."
    ;;
  "verbose")
    ConsoleMessage "Automatic reboot in progress (text mode requested)."
    VerboseFlag="-v"
    ;;
  *)
    ConsoleMessage "Multiuser startup in progress."
    ;;
esac

##
# Are we booting from a CD-ROM?  If so, switch over to /etc/rc.cdrom.
##
if [ -d /System/Installation ] && [ -f /etc/rc.cdrom ]; then
    ##
    # Startup the ATS Server
    ## 
    if [ -f "/System/Library/PrivateFrameworks/ATS.framework/Support/StartATSServer" ]; then
	ConsoleMessage "Starting ATS Server."
        "/System/Library/PrivateFrameworks/ATS.framework/Support/StartATSServer"
    fi
    if [ "${BootType}" != "verbose" ] &&
       [ -x "/System/Library/Frameworks/CoreGraphics.framework/Resources/Window Manager" ]; then
	ConsoleMessage "Starting Window Server."
        "/System/Library/Frameworks/CoreGraphics.framework/Resources/Window Manager"
    fi
    /etc/rc.cdrom ${BootType}
    ConsoleMessage "CD-ROM boot procedure complete."
    halt
    exit 0
fi

##
# Mount essential local filesystems (according to /etc/fstab).
##

ConsoleMessage "Mounting local filesystems"

mount -vat hfs
mount -vat ufs
mount -t fdesc -o union stdin /dev
mkdir -p /.vol && mount_volfs /.vol

##
# Create mach symbol file
##

rm -f /mach.sym

sysctl -n kern.symfile

if [ -f /mach.sym ]; then
  rm -f /mach
  ln -s /mach.sym /mach
else
  rm -f /mach
  ln -s /mach_kernel /mach
fi

sync

##
# Start kextd
##

ConsoleMessage "Configuring kernel extensions."

kextd

##
# This is a hack to deal with resource forks created on UFS during
# the system build.  It should go away.
##
if [ -f /var/log/runFixUpResources ]; then
    /System/Developer/Tools/FixupResourceForks > /var/tmp/FixupResourceForks.log 2>&1
    rm -f /var/log/runFixUpResources
fi

##
# Startup the ATS Server
## 
if [ -f /System/Library/PrivateFrameworks/ATS.framework/Support/StartATSServer ]; then
    ConsoleMessage "Starting ATS Server."
    "/System/Library/PrivateFrameworks/ATS.framework/Support/StartATSServer"
fi

if [ "${BootType}" != "verbose" ] &&
   [ -x "/System/Library/Frameworks/CoreGraphics.framework/Resources/Window Manager" ]; then
    ConsoleMessage "Starting Window Server."
    "/System/Library/Frameworks/CoreGraphics.framework/Resources/Window Manager"
fi

##
# update flushes the cached blocks from the filesystem using
# the sync system call every 30 seconds.  This ensures the
# disk is reasonably up-to-date in the event of a system crash.
##
update

##
# Start the virtual memory system.
##

ConsoleMessage "Starting virtual memory."

swapdir=/private/var/vm

# Make sure the swapfile exists
if [ ! -d ${swapdir} ]; then
    ConsoleMessage "Creating default swap directory."
    mount -uw /
    mkdir -p -m 755 ${swapdir}
    chown root:wheel ${swapdir}
else
    rm -rf ${swapdir}/swap*
fi
		    
dynamic_pager -H 40000000 -L 160000000 -S 80000000 -F ${swapdir}/swapfile

##
# Start System Services
##
SystemStarter ${VerboseFlag}

exit 0
